export const mediumKeywords = [
  "curând",
  "rapid",
  "sensibil la timp",
  "audiere",
  "depoziție",
  "mediere",
  "conferință de soluționare",
];

export const urgentKeywords = [
  "urgent",
  "urgență",
  "imediat",
  "cât mai repede",
  "termen limită",
  "dată proces",
  "audiere mâine",
  "arest",
  "ordin de restricție",
  "ordonanță de protecție",
  "notificare de evacuare",
  "executare silită",
  "faliment",
];

export const legalTerms = [
  "încălcarea contractului",
  "neglijență",
  "răspundere",
  "daune",
  "compensații",
  "tranzacție",
  "ordin judecătoresc",
  "ordonanță de protecție",
  "probațiune",
  "depoziție",
  "mărturie",
  "dovadă",
  "martor",
  "citație",
  "moțiune",
  "audiere",
  "proces",
  "apel",
  "jurisdicție",
  "termen de prescripție",
  "proces echitabil",
];

export const commonTerms = [
  "instanță",
  "judecător",
  "avocat",
  "procuror",
  "client",
  "inculpat",
  "reclamant",
  "pârât",
  "contract",
  "acord",
  "caz",
  "lege",
  "drept",
  "juridic",
  "justiție",
  "drepturi",
  "proprietate",
  "afacere",
  "companie",
  "firmă",
  "corporație",
  "stat",
  "federal",
];
